#!/bin/bash

if [ "$WORKDIR" == "" ]; then
  WORKDIR=$(pwd)
fi

CACHE_PATH="$WORKDIR/cache"
GEONAMES_PATH="$WORKDIR/geonames"
EXTRACT_PATH="$WORKDIR/extract"
ETAG_DIR="$WORKDIR/etag"
INSTALLERS_DIR="$WORKDIR/installers"

PMETRO_FILE="$CACHE_PATH/pMetroSetup.exe"
PMETRO_URL=(
  'https://pmetro.su/download/pMetroSetup.exe'
  'https://pmetro.chpeks.com/download/pMetroSetup.exe'
)

USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0"
