#!/bin/bash

if [ "$WORKDIR" == "" ]; then
  WORKDIR=$(pwd)
fi

CACHE_PATH="$WORKDIR/cache"
GEONAMES_PATH="$WORKDIR/geonames"
EXTRACT_PATH="$WORKDIR/extract"
ETAG_DIR="$WORKDIR/etag"

PMETRO_FILE="$CACHE_PATH/pMetroSetup.exe"
PMETRO_URL=(
  'https://pmetro.su/download/pMetroSetup.exe'
  'https://pmetro.chpeks.com/download/pMetroSetup.exe'
)

